---
title: Alizée Freudenthal Portfolio
timezone: UTC
collections:
  posts:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
    cover-image: 
    small-text: 
    description: 
    order-id: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
author: Alizée Freudenthal
sass:
  sass_dir: assets/css
permalink: pretty
description: is a french graphic designer based in New York City currently working
  at Mother Design.
keywords: 
project-order:
- 1-TheDean
- 2-MNZ1
- Same
- Sunata
- MNZ Lookbook
- Colors Dance
- 
- 
