---
title: Alizée Freudenthal Portfolio
timezone: UTC
collections:
  posts:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
    cover-image: 
    small-text: 
    description: 
    order-id: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
author: Alizée Freudenthal
sass:
  sass_dir: assets/css
permalink: pretty
description: is an art director and graphic designer <br>based in Paris and New York
  City, available for collaborations here, there and everywhere.
keywords: 
project-order:
- Wonder Corps
- Peter & Paul
- PreK
- The Elysian Bar
- el laberinto
- Nasty Galaxy
- Hacker Hub
- 1-TheDean
- Honor
- Marlton Hotel
- 76ers
- CB2 Identity
- NadiaTarr
- 2-MNZ1
- Sunata
- NWO
- Colors Dance
- Same
