---
title: Studio Freudenthal
timezone: UTC
collections:
  posts:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:title/"
    cover-image: 
    small-text: 
    description: 
    order-id: 
- scope:
    path: ''
    type: pages
  values:
    layout: page
author: Studio Freudenthal
sass:
  sass_dir: assets/css
permalink: pretty
description: creates lasting visual identities and bespoke aesthetics for brands and
  companies of today and tomorrow.
keywords: 
project-order:
- Le Rhodia
- Musee Bourdelle
- Peter & Paul
- 1-TheDean
- Hotel du Sentier
- Marlton Hotel
- Same Architectes
- Thor Heyerdahl
- The Elysian Bar
- Débuts — La revue
- el laberinto
- ASH NYC
- 76ers
- Wonder Corps
- Nasty Galaxy
- PreK
- Hacker Hub
- Honor
- CB2 Identity
- NadiaTarr
- 2-MNZ1
- Sunata
- NWO
- Colors Dance
